name: omnidata-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - pip
  - pip:
    - timm==0.4.12
    - matplotlib
    - gradio
    - pillow
    - requests